apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: devlake 
  namespace: devlake 
spec:
  provider:
    aws:
      service: SecretsManager
      region: ${REGION}
      auth:
        jwt:
          serviceAccountRef:
            name: external-secret-devlake
