apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: app-deploy-with-git-repo
  title: App Deploy with Git Repo
  description: Creates a new Gitea Repo and ArgocCD for deploying an App
  tags:
    - app-deploy
    - gitea
    - argocd
spec:
  owner: guest
  type: service
  parameters:
    - title: Provide App Information
      required:
        - appName
      properties:
        appName:
          title: App Name
          type: string
          description: Name of the App
        environment:
          title: Environment
          type: string
          description: The environment (e.g., dev, prod)
          enum: ['dev-cluster', 'prod-cluster', 'in-cluster']
        repoName:
          title: Repo Name of your Gitea Repo
          type: string
          pattern: ^[a-zA-Z0-9-_.]+$
        repoUrl:
          title: Repo URL of your Gitea Repo integrated with Backstage
          type: string
        appNamespace:
          title: App Namespace
          type: string
          description: The namespace where the app should be deployed
          default: default
    - title: Provide Gitea Instance Information
  steps:
    - id: fetch-info
      name: Fetch Info
      action: debug:log
      input:
        message: 'Backstage is hosted at: \${{ parameters.baseUrl }}'
