apiVersion: v1
kind: Service
metadata:
  name: ${{values.appname}}-dora-webhook-svc
  namespace: ${{values.namespace}}
spec:
  type: ClusterIP  # Or ClusterIP if using Ingress
  ports:
    - port: 12000
      targetPort: 12000
      protocol: TCP
      #authSecret:
        #name: 
  selector:
    eventsource-name: ${{values.appname}}-gitea-dora-webhook

---
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: ${{values.appname}}-gitea-dora-webhook
  namespace: ${{values.namespace}}
  labels:
    eventsource-name: ${{values.appname}}-gitea-dora-webhook
spec:
  service:
    ports:
      - port: 12000
        targetPort: 12000
  webhook:
    incidents-webhook:
      port: "12000"
      endpoint: /incidents
      method: POST
    deployments-webhook:
      port: "12000"
      endpoint: /deployments
      method: POST
    pull-requests-webhook:
      port: "12000"
      endpoint: "/pull-requests"
      method: POST

---
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: ${{values.appname}}-gitea-webhook-sensor
  namespace: ${{values.namespace}}
spec:
  template:
    serviceAccountName: ${{values.appname}}-dora-webhook-sa
  dependencies:
    - name: incidents-webhook
      eventSourceName: ${{values.appname}}-gitea-dora-webhook
      eventName: incidents-webhook
    - name: deployments-webhook
      eventSourceName: ${{values.appname}}-gitea-dora-webhook
      eventName: deployments-webhook
    - name: pull-requests-webhook
      eventSourceName: ${{values.appname}}-gitea-dora-webhook
      eventName: pull-requests-webhook
  triggers:
    - template:
        name: incidents-workflow-trigger
        conditions: "incidents-webhook"
        argoWorkflow:
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: ${{values.appname}}-dora-incidents-workflow-
              spec:
                serviceAccountName: ${{values.appname}}-dora-webhook-sa
                entrypoint: process-incident
                workflowTemplateRef:
                  name: incidents-workflow-template
                arguments:
                  parameters:
                    - name: body
                      value: '{{.Input.body}}'
                    - name: headers
                      value: '{{.Input.header}}'
                    - name: url
                      value: http://devlake-ui.devlake.svc.cluster.local:4000
          parameters:
            - src:
                dependencyName: incidents-webhook
                dataKey: body
              dest: spec.arguments.parameters.0.value
            - src:
                dependencyName: incidents-webhook
                dataKey: header
              dest: spec.arguments.parameters.1.value

    - template:
        name: deployments-workflow-trigger
        conditions: "deployments-webhook"
        argoWorkflow:
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: ${{values.appname}}-dora-deployments-workflow-
              spec:
                serviceAccountName: ${{values.appname}}-dora-webhook-sa
                workflowTemplateRef:
                  name: deployments-workflow-template
                arguments:
                  parameters:
                    - name: body
                      value: '{{.Input.body}}'
                    - name: headers
                      value: '{{.Input.header}}'
                    - name: url
                      value: http://devlake-ui.devlake.svc.cluster.local:4000
          parameters:
            - src:
                dependencyName: deployments-webhook
                dataKey: body
              dest: spec.arguments.parameters.0.value
            - src:
                dependencyName: deployments-webhook
                dataKey: header
              dest: spec.arguments.parameters.1.value

    - template:
        name: pull-requests-workflow-trigger
        conditions: "pull-requests-webhook"
        argoWorkflow:
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: ${{values.appname}}-dora-pull-requests-workflow-
              spec:
                serviceAccountName: ${{values.appname}}-dora-webhook-sa
                workflowTemplateRef:
                  name: pull-requests-workflow-template
                entrypoint: process-pull-request
                arguments:
                  parameters:
                    - name: body
                      value: '{{.Input.body}}'
                    - name: headers
                      value: '{{.Input.header}}'
                    - name: url
                      value: http://devlake-ui.devlake.svc.cluster.local:4000
          parameters:
            - src:
                dependencyName: pull-requests-webhook
                dataKey: body
              dest: spec.arguments.parameters.0.value
            - src:
                dependencyName: pull-requests-webhook
                dataKey: header
              dest: spec.arguments.parameters.1.value
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ${{values.appname}}-dora-webhook-ing
  namespace: ${{values.namespace}}
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 512m
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - host: ${{values.hostname}}
      http:
        paths:
          - backend:
              service:
                name: ${{values.appname}}-dora-webhook-svc
                port:
                  number: 12000
            path: /argo-events/${{values.appname}}-dora(/|$)(.*)
            pathType: ImplementationSpecific
    - host: localhost
      http:
        paths:
          - backend:
              service:
                name: ${{values.appname}}-dora-webhook-svc
                port:
                  number: 12000
            path: /argo-events/${{values.appname}}-dora(/|$)(.*)
            pathType: ImplementationSpecific

