apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  description: Create SageMaker Project Templates for Train a model on Abalone dataset with XGBoost, LLM fine-tuning and evaluation, Batch Inference, Huggingface Model Import, Multi-account Model Deployment
  name: sagemaker-project-templates
  title: SageMaker Project Templates
spec:
  owner: guest
  type: service
  parameters:
    - properties:
        tfVars:
          properties:
            aws_region:
              description: AWS Region
              type: string
          title: Terraform variables
          type: object
        adminRoleName:
          default: Admin
          description: Name of the role to give the administrative rights on the EKS cluster.
          title: Admin Role Name
          type: string
        name:
          title: name of this entry
          type: string
        namespace:
          default: flux-system
          title: namespace within the kubernetes cluster to deploy this
          type: string
      title: Configuration Options
  steps:
    - id: fetchSystem
      name: Fetch System
      action: catalog:fetch
      input:
        entityRef: system:default/system-info
    - action: fetch:template
      id: fetch-base
      input:
        url: ./service-catalog-templates/
        values:
          adminRoleName: ${{parameters.adminRoleName}}
          clusterName: ${{ parameters.clusterName }}
          name: ${{ parameters.name }}
          namespace: ${{ parameters.namespace }}
          tfVars: ${{ parameters.tfVars }}
      name: Fetch Base
    - id: publish
      name: Publishing to a gitea git repository
      action: publish:gitea
      input:
        description: Example EKS Cluster with Stateful Workload Demo
        repoUrl: ${{ steps['fetchSystem'].output.entity.spec.hostname }}/gitea?repo=${{parameters.name}}
        defaultBranch: main
    - id: create-argocd-app
      name: Create ArgoCD App
      action: cnoe:create-argocd-app
      input:
        appName: ${{parameters.name}}
        appNamespace: ${{parameters.namespace}}
        argoInstance: in-cluster
        projectName: default
        repoUrl: http://my-gitea-http.gitea.svc.cluster.local:3000/giteaAdmin/${{parameters.name}}
        path: "manifests"
    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps['publish'].output.repoContentsUrl }}
        catalogInfoPath: 'catalog-info.yaml'
  output:
    links:
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps['register'].output.entityRef }}
