apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: create-dev-and-prod-env-${{values.name}}
  description: Create Dev and Prod Clusters ${{ values.name }}
  annotations:
    backstage.io/kubernetes-namespace: ${{values.namespace}}
    backstage.io/kubernetes-id: create-dev-and-prod-env-${{values.name}}
    argo-workflows.cnoe.io/label-selector: env=dev,entity-id=${{values.name}}
    argo-workflows.cnoe.io/cluster-name: local
spec:
  type: service
  lifecycle: experimental
  owner: guest
  system: ${{values.name | dump}}

