---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: devlake-mysql-access-binding
subjects:
- kind: ServiceAccount
  name: devlake-mysql-access
  namespace: devlake
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: Job
metadata:
  name: mysql-user-setup
spec:
  template:
    metadata:
      generateName: mysql-user-setup-
    spec:
      serviceAccountName: devlake-mysql-access
      restartPolicy: OnFailure
      initContainers:
      - name: create-secret
        image: bitnami/kubectl
        command:
          - /bin/bash
          - -c
          - |
            while true; do
                CONN_SECRET_NAME=$(kubectl get secrets -n crossplane-system -o custom-columns=NAME:.metadata.name | grep "^devlake-mysql.*cluster-mysql-connection$" || true)
                if [ -n "$CONN_SECRET_NAME" ]; then
                    break
                fi
                echo "Waiting for secret to be available..."
                sleep 5
            done
            endpoint=$(kubectl get secret ${CONN_SECRET_NAME} -n crossplane-system -o jsonpath='{.data.endpoint}' | base64 --decode)
            kubectl create service externalname devlake-mysql-service --external-name=${endpoint} -n devlake
            password=$(kubectl get secret ${CONN_SECRET_NAME} -n crossplane-system -o jsonpath='{.data.attribute\.master_password}' | base64 --decode)
            kubectl create secret generic devlake-mysql-auth -n devlake \
            --from-literal=MYSQL_USER=merico \
            --from-literal=MYSQL_PASSWORD=merico \
            --from-literal=MYSQL_DATABASE=lake \
            --from-literal=MYSQL_ROOT_PASSWORD=$password \
            --from-literal=DB_URL="mysql://merico:merico@devlake-mysql-service:3306/lake?charset=utf8mb4&parseTime=True"
      containers:
      - name: create-grafana-user
        image: mysql:8
        command: 
          - /bin/bash
          - -c
          - |
            until mysql -h devlake-mysql-service -P 3306 -u root -p${MYSQL_ROOT_PASSWORD} -e "SELECT 1"; do
              echo "Waiting for MySQL to be ready..."
              sleep 2
            done

            mysql -h devlake-mysql-service -P 3306 -u root -p${MYSQL_ROOT_PASSWORD} -e "
            CREATE DATABASE IF NOT EXISTS lake;
            "

            echo "Creating devlake user..."
            mysql -h devlake-mysql-service -P 3306 -u root -p${MYSQL_ROOT_PASSWORD} -e "
            CREATE USER IF NOT EXISTS 'merico' IDENTIFIED BY 'merico';
            GRANT ALL PRIVILEGES ON lake.* TO 'merico';
            FLUSH PRIVILEGES;
            "
          
            echo "Creating Grafana user..."
            mysql -h devlake-mysql-service -P 3306 -u root -p${MYSQL_ROOT_PASSWORD} -e "
            CREATE USER IF NOT EXISTS 'grafanaReader' IDENTIFIED BY 'grafana_password';
            GRANT SELECT ON lake.* TO 'grafanaReader';
            FLUSH PRIVILEGES;
            "

            echo "User creation completed."
        envFrom:
          - secretRef:
              name: devlake-mysql-auth

