apiVersion: core.oam.dev/v1beta1
kind: ComponentDefinition
metadata:
  annotations:
    definition.oam.dev/alias: ""
    definition.oam.dev/description: AWS S3 Bucket
  name: s3-bucket
spec:
  schematic:
    cue:
      template: |
        output: {
                apiVersion: "awsblueprints.io/v1alpha1"
                kind:       "ObjectStorage"
                metadata: name: context.name
                spec: {
                        compositionSelector: matchLabels: {
                                "awsblueprints.io/provider":         "aws"
                                "awsblueprints.io/environment":      parameter.environment
                                "s3.awsblueprints.io/configuration": parameter.configuration
                        }
                        writeConnectionSecretToRef: name: "\(context.name)-info"
                        resourceConfig: {
                                providerConfigName: parameter.providerConfigName
                                region:             parameter.region
                                tags: [
                                    {
                                        key:   "name"
                                        value: context.name
                                    },
                                    {
                                        key: "other"
                                        value: "env"
                                    }
                                ]
                        }
                }
        }
        parameter: {
                environment:        string
                configuration:      string
                providerConfigName: string
                region:             string
        }
  workload:
    definition:
      apiVersion: apps/v1
      kind: Deployment
