apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: microservices-with-git-repo
  title: MicroServices with Gitea Repo
  description: Creates a new Gitea Repo and ArgocCD for deploying a microservice
  tags:
    - microservices
    - gitea
    - argocd
spec:
  owner: guest
  type: service
  parameters:
    - title: Provide Microservice Information
      required:
        - microserviceName
        - environment
        - repoName
      properties:
        microserviceName:
          title: Microservice Name
          type: string
          description: Name of the microservice
        environment:
          title: Environment
          type: string
          description: The environment (e.g., dev, prod)
          enum: ['dev', 'prod']
        repoName:
          title: Repo URL of your Gitea Repo integrated with Backstage
          type: string
          pattern: ^[a-zA-Z0-9-_.]+$
  steps:
    - id: fetch-base
      name: Fetch Skeleton + Template
      action: fetch:template
      input:
        url: ./skeleton
        values:
          microservice_name: ${{ parameters.microserviceName }}
          environment: ${{ parameters.environment }}
    - id: publish
      name: Publishing to a gitea git repository
      action: publish:gitea
      input:
        description: Microservice ${{parameters.microserviceName}} for ${{parameters.environment}}
        repoUrl: ${{parameters.repoUrl}}?repo=${{parameters.repoName}}
        defaultBranch: main
    - id: create-argocd-app
      name: Create ArgoCD App
      action: cnoe:create-argocd-app
      input:
        appName: ${{parameters.microserviceName}}
        argoInstance: in-cluster
        projectName: default
        repoUrl: http://my-gitea-http.gitea.svc.cluster.local:3000/giteaAdmin/${{parameters.repoName}}
        path: "manifests"
    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: '/catalog-info.yaml'
    - id: template-output
      name: Template Output
      action: debug:log
      input:
        listWorkspace: true

  output:
    links:
      - title: Repository
        url: ${{ steps.publish.output.remoteUrl }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}
