apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: northwind
spec:
  components:
    - name: northwind-ux 
      type: appmod-service
      properties:
        image:  929819487611.dkr.ecr.us-west-2.amazonaws.com/moderneng/northwind:latest
        image_name: northwind
        port: 80
        targetPort: 80
        # functionalGate:
        #   pause: "10s" 
        #   image: "public.ecr.aws/i8e1q7x5/appmod-javafunctest:latest"
        #   extraArgs: "red"
        # performanceGate:
        #   pause: "10s"
        #   image: "public.ecr.aws/i8e1q7x5/javaperftest:latest"
        #   extraArgs: "160"
      traits: 
        - type: path-based-ingress
          properties:
            domain: "*.elb.us-west-2.amazonaws.com"
            rewritePath: true 
            http:
              /northwind-app: 80
      
