apiVersion: rds.aws.upbound.io/v1beta2
kind: Instance
metadata:
  annotations:
    meta.upbound.io/example-id: rds/v1beta1/instance
  labels:
    testing.upbound.io/example-name: northwind-dbinstance
  name: northwind-dbinstance-random
spec:
  forProvider:
    allocatedStorage: 20
    autoGeneratePassword: true
    autoMinorVersionUpgrade: true
    backupRetentionPeriod: 2
    backupWindow: 09:46-10:16
    engine: sqlserver-ex
    engineVersion: "16.00.4140.3.v1"
    instanceClass: db.t3.medium
    identifier: "northwind-db"
    passwordSecretRef:
      key: password
      name: northwind-dbinstance
      namespace: team-n
    publiclyAccessible: false
    region: us-west-2
    skipFinalSnapshot: true
    username: adminuser
  writeConnectionSecretToRef:
    name: northwinde-dbinstance-out
    namespace: team-n
