apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.appname}}-dora
  description: Onboard ${{ values.appname }} team to DORA monitoring
  annotations:
    backstage.io/kubernetes-namespace: ${{values.namespace}}
    backstage.io/kubernetes-label-selector: 'entity-id=${{values.appname}}-dora'
    argocd/app-selector: 'entity-id=${{values.appname}}-dora'
    argo-workflows.cnoe.io/cluster-name: local
    argo-workflows.cnoe.io/namespace: ${{values.namespace}}
    argo-workflows.cnoe.io/label-selector: 'entity-id=${{values.appname}}-dora'
  links:
    - url: https://${{values.hostname}}/gitea?repo=${{values.appname}}-dora
      title: Repo URL
      icon: github
spec:
  type: service
  lifecycle: experimental
  owner: guest
  system: ${{values.appname | dump}}

