apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: microservice-${{values.microserviceName}}
  description: Microservice for ${{values.microserviceName}}
  annotations:
    backstage.io/kubernetes-namespace: backstage
    argocd/app-name: ${{values.name | dump}}
spec:
  type: micro-service
  lifecycle: experimental
  owner: guest
  system: ${{values.microserviceName | dump}}