apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: microservices-without-git-repo
  title: MicroServices with Git Repo
  description: Creates a ArgocCD for deploying a microservice for an existing Git Repo
  tags:
    - microservices
    - gitea
    - argocd
spec:
  owner: guest
  type: service
  parameters:
    - title: Provide Microservice Information
      required:
        - microserviceName
        - repoPath
        - repoName
      properties:
        microserviceName:
          title: Microservice Name
          type: string
          description: Name of the microservice
        repoName:
          title: Repo URL of your Gitea Repo integrated with Backstage
          type: string
          pattern: ^[a-zA-Z0-9-_.]+$
        repoPath:
          title: Path of Git Repo to sync for GitOps
          type: string
  steps:
    - id: create-argocd-app
      name: Create ArgoCD App
      action: cnoe:create-argocd-app
      input:
        appName: ${{parameters.microserviceName}}
        argoInstance: in-cluster
        projectName: default
        repoUrl: http://my-gitea-http.gitea.svc.cluster.local:3000/giteaAdmin/${{parameters.repoName}}
        path: ${{parameters.repoPath}}
    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: '/catalog-info.yaml'
    - id: template-output
      name: Template Output
      action: debug:log
      input:
        listWorkspace: true

  output:
    links:
      - title: Repository
        url: ${{ steps.publish.output.remoteUrl }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}
