apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: modern-engg
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: For the modern-engg project
  sourceRepos:
    - '*'
  sourceNamespaces:
    - team-*
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - namespace: ack-system
      server: https://kubernetes.default.svc
    - namespace: cert-manager
      server: https://kubernetes.default.svc
    - namespace: default
      server: https://kubernetes.default.svc
    - namespace: dapr-system
      server: https://kubernetes.default.svc
    - namespace: devlake
      server: https://kubernetes.default.svc
    - namespace: ingress-nginx
      server: https://kubernetes.default.svc
    - namespace: kyverno
      server: https://kubernetes.default.svc
    - namespace: argo-events
      server: https://kubernetes.default.svc
    - namespace: jupyterhub
      server: https://kubernetes.default.svc
    - namespace: aws-load-balancer-controller
      server: https://kubernetes.default.svc
    - namespace: external-dns
      server: https://kubernetes.default.svc
    - namespace: external-secrets
      server: https://kubernetes.default.svc
    - namespace: keycloak
      server: https://kubernetes.default.svc
    - namespace: argo
      server: https://kubernetes.default.svc
    - namespace: modernengg-workflows 
      server: https://kubernetes.default.svc
    - namespace: spark-operator
      server: https://kubernetes.default.svc
    - namespace: crossplane-system
      server: https://kubernetes.default.svc
    - namespace: vela-system
      server: https://kubernetes.default.svc
    - namespace: backstage
      server: https://kubernetes.default.svc
    - namespace: data-on-eks
      server: https://kubernetes.default.svc
    - namespace: tf-eks-observability
      server: https://kubernetes.default.svc
    - name: dev-cluster
      namespace: team-*
    - name: prod-cluster
      namespace: team-*
