apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: ${{values.appname}}-dora-provisioning-
  namespace: ${{values.namespace}}
  labels:
    entity-id: ${{values.appname}}-dora
spec:
  volumeClaimTemplates:
  - metadata:
      name: workdir
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: gp3
      resources:
        requests:
          storage: 256Mi

  entrypoint: main
  serviceAccountName: ${{values.appname}}-dora-provisioner
  arguments:
    parameters:
    - name: appname
      value: ${{values.appname}}
    - name: namespace
      value: ${{values.namespace}}
    - name: hostname
      value: ${{values.hostname}}
    - name: apprepo
      value: ${{values.hostname}}/gitea/giteaAdmin/${{values.appname}}

  templates:
  - name: main
    steps:
    - - name: run-provisioner
        templateRef:
          name: dora-provisioner-template
          template: dora-provisioner
        arguments:
          parameters:
          - name: appname
            value: "{{workflow.parameters.appname}}"
          - name: namespace
            value: "{{workflow.parameters.namespace}}"

    - - name: run-data-gen
        templateRef:
          name: dora-data-gen-template
          template: dora-data-gen
